// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcjzxnxvacejdujfmoaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhjanp4bnh2YWNlamR1amZtb2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MTY1NTYsImV4cCI6MjA2MTM5MjU1Nn0.cXDOsXhnQSyTSHxbz0NIql1IcVpOUjPWB7ua1Vstykc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);